language: ruby
rvm:
- 2.1
script: bundle exec jekyll build && bundle exec htmlproof ./_site --href-ignore https://www.linkedin.com/in/abremges

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

notifications:
  email:
  - andreas@bremges.de
