language: ruby
rvm:
- 2.3.3
script: bundle exec jekyll build && bundle exec htmlproofer ./_site

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false

notifications:
  email:
  - andreas@bremges.de
