---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: / ## disables post output
timezone: null
lsi: false
markdown: kramdown
highlighter: pygments


### content configuration ###
title:       "Andreas Bremges"
keywords:    "andreas, bremges, bioinformatics, metagenomics, single cell, assembly, microbial dark matter"
description: "Landing page of Andreas Bremges."
source_link: "https://github.com/t413/SinglePaged"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: UA-60416689-1 ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:		'#4d4d4d'
  white:		'#F3EDE1'
  briwhite: '#FFFFFF'
  warmgray1:		'#A9A59D'
  warmgray2:		'#78746F'
  warmgray3:		'#4B4945'
  gray1:    '#EFEFEF'
  gray2:    '#DEDEDE'
  gray3:    '#CDCDCD'
  red:      '#FF3636'
  blue:			'#49a7e9'
  green:		'#9bcf2f'
  purple:		'#c869bf'
  orange:		'#fab125'
  turquoise:	'#0fbfcf'
  Gy1:    '#e0e0e0'
  Gy2:    '#bababa'
  Gy3:    '#878787'
  Gy4:    '#4d4d4d'
  Gy5:    '#1a1a1a'
  Rd1:    '#fddbc7'
  Rd2:    '#f4a582'
  Rd3:    '#d6604d'
  Rd4:    '#b2182b'
  Rd5:    '#67001f'
